query About {
	about {
		...AboutFragment
	}
}

fragment AboutFragment on AboutRecord {
	__typename
	id
	description(markdown: false)
	address(markdown: false)
	hours
	email
	phone
	googleMapsUrl
	image {
		...ImageFragment
	}
	privacyPolicy(markdown: false)
}

fragment AboutFragmentLight on AboutRecord {
	__typename
	id
	image {
		...ImageFragment
	}
}
