query Start {
	start {
		__typename
		id
		links {
			... on HappeningRecord {
				_modelApiKey
				_editingUrl
				...HappeningFragmentLight
			}
			... on ExhibitionRecord {
				_modelApiKey
				_editingUrl
				...ExhibitionFragmentLight
			}
			... on ExternalLinkRecord {
				_modelApiKey
				_editingUrl
				...ExternalLinkFragment
			}
		}
	}
}
